# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/shaoyaoqian"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/PengfeiMa657387"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "email"
name = "Email"
url = "mailto:499908174@qq.com"

[social.params]
icon = "mail"

[[social]]
identifier = "zhihu"
name = "Zhihu"
url = "mailto:499908174@qq.com"

[social.params]
icon = "zhihu"

[[social]]
identifier = "weibo"
name = "Weibo"
url = "mailto:499908174@qq.com"

[social.params]
icon = "weibo"
