# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/favicon.png"
# author = "Pengfei Ma"
theauthor = "Ma Pengfei"

[footer]
since = 2020
customText = "<a href=\"https://beian.miit.gov.cn\">浙ICP备2022032946号-1</a>"

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = ""
# subtitle = "卮言日出,和以天倪"

[sidebar.avatar]
enabled = true
local = true
src = "img/portrait.jpg"

[article]
headingAnchor = false
math = false
readingTime = true

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "thanks"

[[widgets.homepage]]
type = "aplayer"

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "artalk"

[comments.artalk]
server = 'https://comments.pengfeima.cn'
site = 'Hugo'
css = 'https://comments.pengfeima.cn/dist/Artalk.css'
js = 'https://comments.pengfeima.cn/dist/Artalk.js'
